### PR TITLE
feat: Add ability to set room ID as timer endpoint

### PR DESCRIPTION
**Pull request by caeyo**
Allows the user to specify a particular room ID to act as an endpoint so that the timer stops on entering that room.

Changes:
- Add "Set Room ID as End Point" hotkey - when in the debug map, if this key is pressed while the mouse is hovering over a valid room (has at least one spawnpoint and is not a filler room), that room's ID will become the new Room ID End Point. 
Uses the `TestCheck()` method in `Celeste.Editor.MapEditor` to get the level underneath the cursor, which is tracked by the `mousePosition` field in that class - both of these are private, originally I used `DynamicData.For` to get them but then I realised there are reflection utils in SRTool so I made use of those instead, as I didn't want to bump the project's MonoMod/Cecil versions unnecessarily.
   - When pressing this hotkey, a message indicating that the Room ID End Point has been set to that level will appear in the bottom-left of the debug map and persist for 1 second. 
   I couldn't find a way to get this message to render without hooking the `MapEditor.Render()` method itself and making sure it was drawn after the rest of the debug map overlay - I didn't find any issues with it in my testing, but you're far more experienced than me so if there's a better way of doing this then I'm all ears.
- Add "Clear Room ID End Point" hotkey - sets the Room ID End Point to an empty string, pretty similar to the key used to get rid of flag endpoints.
- Add a "Room ID End Point: {roomID}" entry to the Room Timer section of SRTool's options. 
This is only shown when there is a room ID to end on since I personally thought that was cleaner, but that's easily changed if you'd prefer it to persist there and display nothing. Also made it non-selectable since it has no function otherwise.
- Account for room ID in timer behaviour, essentially treated as another flag end point.

Notes:
- I wasn't sure where to put the `MapEditor.Render()` hook - let me know if that'd be more appropriate in a different class.
- I originally wanted to have a menu button to open a text prompt and allow the user to enter the room ID string manually, however there doesn't seem to be any Everest/vanilla support for doing that while in a level (only in the overworld) which would mostly defeat the purpose of a menu like that. I think it's possible to build a string input menu for use in-game from scratch, but a: I didn't feel confident tackling that myself, and b: the hotkey should be a far more efficient and intuitive solution for the end-user anyway. If you've got any ideas on how to handle a menu like that then let me know, but I don't think I'll be implementing that myself unless somebody can convince me to or I suddenly feel like doing it.
- I opted to treat the room ID as basically an end point for timing purposes rather than a third timing mechanism alongside end points and room count, mostly because it was easier than wrapping my head around the time key system 😅 there was some interest in it being a third mechanism, but given how easy it is to clear the room ID with a hotkey I can't see it being a sore point. I might try implement that at some point though if nobody else gets to it first.

Demonstration:
https://user-images.githubusercontent.com/72244655/170931951-9d40de67-31f5-4939-a4d3-1215432464f2.mp4

### CODE REVIEW

**Comment by DemoJameson** [comment]
nice feature
as I understand it, Room ID EndPoint should be consistent with the normal EndPoint, so there is no need to add additional hotkeys and setting
we can reuse set endpoint and reset timer hotkeys, and the room id can be saved in EndPoint

btw I found that the reset timer hotkey don't popup tooltip, I will add it later

**Comment by caeyo** [comment]
Room ID EndPoint should be consistent from the timer behaviour perspective, however I went with separate hotkeys to allow for use of Flag EndPoints without overwriting/clearing the Room ID EndPoint. E.g. if I'm doing segment practice with a Room ID EndPoint, I may want to pause briefly to time something in one of the rooms using Flags - once I finish with that timing, I don't necessarily want to clear my Room ID and then have to go back into the debug map to set it again. I guess the current handling of this use-case isn't great, since ideally we'd be tracking PBs set on a Room ID EndPoint separate to Flag EndPoints, but yeah I didn't really grasp what was going on with the timeKey stuff to figure out how to do that.

Reusing the set endpoint key seems fine though - hopefully that won't be hard to figure out on the user-side

**Comment by DemoJameson** [comment]
do you mind I remove those hotkeys after the merge
because I want to avoid introducing hotkeys as much as possible
and I'll modify the text of the current hotkeys to fit this new feature
I might also add some indicators for users to find the room endpoint when reopening the debug map

**Comment by caeyo** [comment]
That's perfectly understandable! I gave it a bit more thought and I'm now totally fine with removing those hotkeys, and saving the room ID in EndPoint - it's functionally the same as an endpoint and should probably just be treated as such across the board. 

There's also been some interest in adding support for more timer end conditions, e.g. ending on cassette touches or heart collects for timing segments (particularly with the new segment leaderboard that would benefit from a consistent endpoint), badeline orb touches and strawberry collects for timing strats, etc. With this conversation regarding the room ID feature in mind, what do you think about these conditions + the room ID condition being implemented via a refactor of EndPoint to create different kinds of endpoints based on these conditions? Might make it easier to add new end conditions as people request them, could maybe achieve this by:
- Adding separate classes for each endpoint condition that inherit from the current EndPoint class (e.g. RoomIDEndPoint, CassetteEndPoint, HeartEndPoint, etc), and moving everything flag-related (e.g. the confetti render and sprite stuff) in the current EndPoint to its own FlagEndPoint class. Can make methods like StopTime and ReadyForTime virtual to allow each endpoint to define overrides as well
- Having an enum setting to toggle what type of endpoint is created when pressing the create endpoint/additional endpoint key, so no extra hotkeys for adding new endpoints (although maybe one would be nice for cycling through that enum)
- And they'd all be removed when pressing the reset time key, which is fine imo

If you'd prefer not to add this support at all that's totally fine - it's your mod, I definitely don't want to be overbearing 😅 although stuff like cassette splits in particular have been mentioned a number of times in celestecord, and I think the new segment sheet managers wanted to approach you eventually about adding it as well.
If you've got any alternative ideas for this kind of end condition support then let me know, but if you would like to see it then I'm happy to close this PR and build this myself on a new branch.

**Comment by DemoJameson** [comment]
> ending on cassette touches or heart collects for timing segments

Might add limited support for cassette/heart, similar to the flags in chapter 7 3000m, think of it as a room that can be toggled on and off with an option

**Comment by caeyo** [comment]
Sounds good, will let you handle it then. Let me know if you need testing

**Pull request merged**
